import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/components/Navbar";
import Loader from "@/components/Loader";
import { Toaster } from "react-hot-toast";
import { AppProvider } from "@/context/AppProvider";
import App from "next/app";
export const metadata: Metadata = {
  title: "My NextJs App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
        < Toaster />
        < Navbar />
        {children}
        </AppProvider>
      </body>
    </html>
  );
}
